stages:
  preprocess_data:
    cmd: python credit_score_mlops/data_preprocessing.py data/raw/credit_risk_dataset.csv data/processed/train.csv data/processed/test.csv
    deps:
    - params.yaml
    - credit_score_mlops/data_preprocessing.py
    - data/raw/credit_risk_dataset.csv
    params:
    - target
    - data_preprocessing.random_state
    - data_preprocessing.test_size
    # outs:
    # - data/processed/test.csv
    # - data/processed/train.csv
  train:
    cmd: python credit_score_mlops/modeling/train.py data/processed/train.csv data/processed/test.csv models/model.pkl
    deps:
    - params.yaml
    - credit_score_mlops/modeling/train.py
    - credit_score_mlops/modeling/woe_logistic_regression.py
    - credit_score_mlops/utils.py
    - credit_score_mlops/plots.py
    - data/processed/train.csv
    - data/processed/test.csv
    params:
    - target
    - train.model_params
    - train.train_calibration_curve_file
    - train.test_calibration_curve_file
    # outs:
    # - models/model.pkl
    # - reports/figures/train_calibration_curve.png
    # - reports/figures/test_calibration_curve.png