stages:
  preprocess_data:
    cmd: python credit_score_mlops/data_preprocessing.py data/raw/credit_risk_dataset.csv
      data/processed/train.csv data/processed/test.csv
    deps:
    - params.yaml
    - credit_score_mlops/data_preprocessing.py
    - data/raw/credit_risk_dataset.csv
    params:
    - target
    - data_preprocessing.random_state
    - data_preprocessing.test_size
    outs:
    - data/processed/test.csv
    - data/processed/train.csv
  train:
    cmd: python credit_score_mlops/modeling/train.py data/processed/train.csv models/model.pkl
    deps:
    - params.yaml
    - credit_score_mlops/modeling/train.py
    - data/processed/train.csv
    params:
    - target
    - train.logreg_params
    - train.woe_transformer_params
    outs:
    - models/model.pkl
  evaluate:
    cmd: python credit_score_mlops/modeling/evaluate.py models/model.pkl data/processed/train.csv
      data/processed/test.csv
    deps:
    - params.yaml
    - credit_score_mlops/modeling/evaluate.py
    - data/processed/test.csv
    - data/processed/train.csv
    - models/model.pkl
    params:
    - target
    - evaluate.train_metrics_file
    - evaluate.test_metrics_file
    - evaluate.train_calibration_curve_file
    - evaluate.test_calibration_curve_file
    metrics:
    - reports/train_metrics.json:
        cache: false
    - reports/test_metrics.json:
        cache: false
    outs:
    - reports/figures/train_calibration_curve.png
    - reports/figures/test_calibration_curve.png