stages:
  preprocess_data:
    cmd: python credit_score_mlops/data_preprocessing.py data/raw/credit_risk_dataset.csv
      data/processed/train.csv data/processed/test.csv
    deps:
    - credit_score_mlops/data_preprocessing.py
    - data/raw/credit_risk_dataset.csv
    outs:
    - data/processed/test.csv
    - data/processed/train.csv
    params:
    - data_preprocessing.random_state
    - target
    - data_preprocessing.test_size
  train:
    cmd: python credit_score_mlops/modeling/train.py data/processed/train.csv models/model.pkl
    deps:
    - credit_score_mlops/modeling/train.py
    - data/processed/train.csv
    params:
    - train.logreg_params
    - target
    - train.woe_transformer_params
    outs:
    - models/model.pkl
  evaluate:
    cmd: python credit_score_mlops/modeling/evaluate.py models/model.pkl data/processed/train.csv
      data/processed/test.csv
    deps:
    - credit_score_mlops/modeling/evaluate.py
    - data/processed/test.csv
    - data/processed/train.csv
    params:
    - target
    metrics:
    - reports/metrics.json:
        cache: false
    plots:
    - reports/plots/sklearn/train_calibration.json:
        template: simple
        x: prob_pred
        y: prob_true
        title: Calibration Curve
        x_label: Mean Predicted Probability
        y_label: Fraction of Positives
        cache: false
    - reports/plots/sklearn/test_calibration.json:
        template: simple
        x: prob_pred
        y: prob_true
        title: Calibration Curve
        x_label: Mean Predicted Probability
        y_label: Fraction of Positives
        cache: false

