target: "loan_status"
data_preprocessing:
  test_size: 0.3
  random_state: 42

train:
  woe_transformer_params: {
    "numerical_columns": ["person_age", "person_income", "person_emp_length", "loan_amnt", "loan_int_rate", "loan_percent_income", "cb_person_cred_hist_length"],
    "categorical_columns": ["person_home_ownership", "loan_intent", "loan_grade", "cb_person_default_on_file"],
    "bins": 5
  }
  logreg_params: {"random_state": 42}