name: Continuous Integration

on:
  push:
    branches:
      - update
  
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: iterative/setup-cml@v2
      - uses: iterative/setup-dvc@v1
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10.14' 
      - name: Install Packages
        run: make requirements
      - name: Formatting
        run: make format
      - name: Linting
        run: make lint
      - name: Configuring Remote DVC Storage
        env:
          ACCESS_KEY_ID: ${{ secrets.DVC_REMOTE_S3_ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.DVC_REMOTE_S3_SECRET_ACCESS_KEY }}
        run: |
          dvc remote add --force origin s3://dvc
          dvc remote modify origin endpointurl https://dagshub.com/marcellinus-witarsah/credit-score-mlops.s3
          dvc remote modify origin --local access_key_id $ACCESS_KEY_ID
          dvc remote modify origin --local secret_access_key $SECRET_ACCESS_KEY
      - name: Pulling Data from Remote S3 Remote Storage via DVC
        run: |
          dvc pull
      - name: Running Pipelines using DVC
        env:
          DAGSHUB_REPOSITORY_NAME: ${{ secrets.DAGSHUB_REPOSITORY_NAME }}
          DAGSHUB_USER_NAME: ${{ secrets.DAGSHUB_USER_NAME }}
          DAGSHUB_PASSWORD: ${{ secrets.DAGSHUB_PASSWORD }}
        run: |
          dvc repro
          dvc push
      - name: Create CML Report
        env:
            REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --depth=1 origin main:main 
          echo 'Metrics Comparison' >> report.md
          dvc metrics diff --md main >> report.md
          echo 'Train Calibration Curve' >> report.md
          echo '![](./reports/figures/train_calibration_curve.png "Training Calibration Curve")' >> report.md
          echo 'Test Calibration Curve' >> report.md
          echo '![](./reports/figures/test_calibration_curve.png "Testing Calibration Curve")' >> report.md
          cml comment create report.md
      - name: Cleaning Complied Python Files
        run: make clean

