name: Continuous Integration

on: [push, workflow_dispatch]
  
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: iterative/setup-cml@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10.14' 
      - name: Install Packages
        run: make requirements
      - name: Formatting
        run: make format
      - name: Linting
        run: make lint
      - name: Running Data Preprocessing and Model Training Pipelines
        run: dvc repro
      - name: Cleaning Complied Python Files
        run: make clean